apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasty-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nastycontainer
  template:
    metadata:
      labels:
        app: nastycontainer
    spec:
      containers:
      - name: nastycontainer
        image: stevenfeltner/nastycontainer
        imagePullPolicy: Always
        command: ["/app/entrypoint.sh", "-s"]
        securityContext:
          privileged: true

